# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fraud_detection.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x05\x66raud\"D\n\x11\x43heckOrderRequest\x12\x13\n\x0btotalAmount\x18\x01 \x01(\x02\x12\x1a\n\x05items\x18\x02 \x03(\x0b\x32\x0b.fraud.Item\"&\n\x04Item\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"5\n\x12\x43heckOrderResponse\x12\x0f\n\x07isFraud\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t2Z\n\x15\x46raudDetectionService\x12\x41\n\nCheckOrder\x12\x18.fraud.CheckOrderRequest\x1a\x19.fraud.CheckOrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHECKORDERREQUEST']._serialized_start=32
  _globals['_CHECKORDERREQUEST']._serialized_end=100
  _globals['_ITEM']._serialized_start=102
  _globals['_ITEM']._serialized_end=140
  _globals['_CHECKORDERRESPONSE']._serialized_start=142
  _globals['_CHECKORDERRESPONSE']._serialized_end=195
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=197
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=287
# @@protoc_insertion_point(module_scope)
