# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import logger_pb2 as logger__pb2


class LoggerServiceStub(object):
    """Our new gRPC service name
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LogInfo = channel.unary_unary(
                '/logger.LoggerService/LogInfo',
                request_serializer=logger__pb2.LogRequest.SerializeToString,
                response_deserializer=logger__pb2.LogResponse.FromString,
                )
        self.LogDebug = channel.unary_unary(
                '/logger.LoggerService/LogDebug',
                request_serializer=logger__pb2.LogRequest.SerializeToString,
                response_deserializer=logger__pb2.LogResponse.FromString,
                )
        self.LogWarn = channel.unary_unary(
                '/logger.LoggerService/LogWarn',
                request_serializer=logger__pb2.LogRequest.SerializeToString,
                response_deserializer=logger__pb2.LogResponse.FromString,
                )
        self.LogError = channel.unary_unary(
                '/logger.LoggerService/LogError',
                request_serializer=logger__pb2.LogRequest.SerializeToString,
                response_deserializer=logger__pb2.LogResponse.FromString,
                )


class LoggerServiceServicer(object):
    """Our new gRPC service name
    """

    def LogInfo(self, request, context):
        """The method the Orchestrator will call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogDebug(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogWarn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogError(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoggerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LogInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.LogInfo,
                    request_deserializer=logger__pb2.LogRequest.FromString,
                    response_serializer=logger__pb2.LogResponse.SerializeToString,
            ),
            'LogDebug': grpc.unary_unary_rpc_method_handler(
                    servicer.LogDebug,
                    request_deserializer=logger__pb2.LogRequest.FromString,
                    response_serializer=logger__pb2.LogResponse.SerializeToString,
            ),
            'LogWarn': grpc.unary_unary_rpc_method_handler(
                    servicer.LogWarn,
                    request_deserializer=logger__pb2.LogRequest.FromString,
                    response_serializer=logger__pb2.LogResponse.SerializeToString,
            ),
            'LogError': grpc.unary_unary_rpc_method_handler(
                    servicer.LogError,
                    request_deserializer=logger__pb2.LogRequest.FromString,
                    response_serializer=logger__pb2.LogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'logger.LoggerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LoggerService(object):
    """Our new gRPC service name
    """

    @staticmethod
    def LogInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/logger.LoggerService/LogInfo',
            logger__pb2.LogRequest.SerializeToString,
            logger__pb2.LogResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LogDebug(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/logger.LoggerService/LogDebug',
            logger__pb2.LogRequest.SerializeToString,
            logger__pb2.LogResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LogWarn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/logger.LoggerService/LogWarn',
            logger__pb2.LogRequest.SerializeToString,
            logger__pb2.LogResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LogError(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/logger.LoggerService/LogError',
            logger__pb2.LogRequest.SerializeToString,
            logger__pb2.LogResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
