# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logger.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0clogger.proto\x12\x06logger\"\x1d\n\nLogRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"0\n\x0bLogResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08isLogged\x18\x02 \x01(\x08\x32?\n\rLoggerService\x12.\n\x03Log\x12\x12.logger.LogRequest\x1a\x13.logger.LogResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logger_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOGREQUEST']._serialized_start=24
  _globals['_LOGREQUEST']._serialized_end=53
  _globals['_LOGRESPONSE']._serialized_start=55
  _globals['_LOGRESPONSE']._serialized_end=103
  _globals['_LOGGERSERVICE']._serialized_start=105
  _globals['_LOGGERSERVICE']._serialized_end=168
# @@protoc_insertion_point(module_scope)
