# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_queue.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11order_queue.proto\x12\norderqueue\"F\n\x0e\x45nqueueRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x11\n\torderData\x18\x02 \x01(\t\x12\x10\n\x08priority\x18\x03 \x01(\x05\"3\n\x0f\x45nqueueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x10\n\x0e\x44\x65queueRequest\"W\n\x0f\x44\x65queueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07orderId\x18\x03 \x01(\t\x12\x11\n\torderData\x18\x04 \x01(\t2\x9b\x01\n\x11OrderQueueService\x12\x42\n\x07\x45nqueue\x12\x1a.orderqueue.EnqueueRequest\x1a\x1b.orderqueue.EnqueueResponse\x12\x42\n\x07\x44\x65queue\x12\x1a.orderqueue.DequeueRequest\x1a\x1b.orderqueue.DequeueResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_queue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ENQUEUEREQUEST']._serialized_start=33
  _globals['_ENQUEUEREQUEST']._serialized_end=103
  _globals['_ENQUEUERESPONSE']._serialized_start=105
  _globals['_ENQUEUERESPONSE']._serialized_end=156
  _globals['_DEQUEUEREQUEST']._serialized_start=158
  _globals['_DEQUEUEREQUEST']._serialized_end=174
  _globals['_DEQUEUERESPONSE']._serialized_start=176
  _globals['_DEQUEUERESPONSE']._serialized_end=263
  _globals['_ORDERQUEUESERVICE']._serialized_start=266
  _globals['_ORDERQUEUESERVICE']._serialized_end=421
# @@protoc_insertion_point(module_scope)
