# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import order_executor_pb2 as order__executor__pb2


class OrderExecutorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DequeueAndExecute = channel.unary_unary(
                '/orderexecutor.OrderExecutorService/DequeueAndExecute',
                request_serializer=order__executor__pb2.DequeueRequest.SerializeToString,
                response_deserializer=order__executor__pb2.DequeueResponse.FromString,
                )
        self.Election = channel.unary_unary(
                '/orderexecutor.OrderExecutorService/Election',
                request_serializer=order__executor__pb2.ElectionRequest.SerializeToString,
                response_deserializer=order__executor__pb2.ElectionResponse.FromString,
                )
        self.Coordinator = channel.unary_unary(
                '/orderexecutor.OrderExecutorService/Coordinator',
                request_serializer=order__executor__pb2.CoordinatorRequest.SerializeToString,
                response_deserializer=order__executor__pb2.CoordinatorResponse.FromString,
                )
        self.GetLeader = channel.unary_unary(
                '/orderexecutor.OrderExecutorService/GetLeader',
                request_serializer=order__executor__pb2.GetLeaderRequest.SerializeToString,
                response_deserializer=order__executor__pb2.GetLeaderResponse.FromString,
                )


class OrderExecutorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DequeueAndExecute(self, request, context):
        """Order execution RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Election(self, request, context):
        """Leader election RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Coordinator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderExecutorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DequeueAndExecute': grpc.unary_unary_rpc_method_handler(
                    servicer.DequeueAndExecute,
                    request_deserializer=order__executor__pb2.DequeueRequest.FromString,
                    response_serializer=order__executor__pb2.DequeueResponse.SerializeToString,
            ),
            'Election': grpc.unary_unary_rpc_method_handler(
                    servicer.Election,
                    request_deserializer=order__executor__pb2.ElectionRequest.FromString,
                    response_serializer=order__executor__pb2.ElectionResponse.SerializeToString,
            ),
            'Coordinator': grpc.unary_unary_rpc_method_handler(
                    servicer.Coordinator,
                    request_deserializer=order__executor__pb2.CoordinatorRequest.FromString,
                    response_serializer=order__executor__pb2.CoordinatorResponse.SerializeToString,
            ),
            'GetLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLeader,
                    request_deserializer=order__executor__pb2.GetLeaderRequest.FromString,
                    response_serializer=order__executor__pb2.GetLeaderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orderexecutor.OrderExecutorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderExecutorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DequeueAndExecute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orderexecutor.OrderExecutorService/DequeueAndExecute',
            order__executor__pb2.DequeueRequest.SerializeToString,
            order__executor__pb2.DequeueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Election(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orderexecutor.OrderExecutorService/Election',
            order__executor__pb2.ElectionRequest.SerializeToString,
            order__executor__pb2.ElectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Coordinator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orderexecutor.OrderExecutorService/Coordinator',
            order__executor__pb2.CoordinatorRequest.SerializeToString,
            order__executor__pb2.CoordinatorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orderexecutor.OrderExecutorService/GetLeader',
            order__executor__pb2.GetLeaderRequest.SerializeToString,
            order__executor__pb2.GetLeaderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
