# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_executor.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14order_executor.proto\x12\rorderexecutor\"\x12\n\x10GetLeaderRequest\"%\n\x11GetLeaderResponse\x12\x10\n\x08leaderId\x18\x01 \x01(\x05\"\x10\n\x0e\x44\x65queueRequest\"W\n\x0f\x44\x65queueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07orderId\x18\x03 \x01(\t\x12\x11\n\torderData\x18\x04 \x01(\t\"#\n\x0f\x45lectionRequest\x12\x10\n\x08senderId\x18\x01 \x01(\x05\"(\n\x10\x45lectionResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\"&\n\x12\x43oordinatorRequest\x12\x10\n\x08leaderId\x18\x01 \x01(\x05\"&\n\x13\x43oordinatorResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xdd\x02\n\x14OrderExecutorService\x12R\n\x11\x44\x65queueAndExecute\x12\x1d.orderexecutor.DequeueRequest\x1a\x1e.orderexecutor.DequeueResponse\x12K\n\x08\x45lection\x12\x1e.orderexecutor.ElectionRequest\x1a\x1f.orderexecutor.ElectionResponse\x12T\n\x0b\x43oordinator\x12!.orderexecutor.CoordinatorRequest\x1a\".orderexecutor.CoordinatorResponse\x12N\n\tGetLeader\x12\x1f.orderexecutor.GetLeaderRequest\x1a .orderexecutor.GetLeaderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_executor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETLEADERREQUEST']._serialized_start=39
  _globals['_GETLEADERREQUEST']._serialized_end=57
  _globals['_GETLEADERRESPONSE']._serialized_start=59
  _globals['_GETLEADERRESPONSE']._serialized_end=96
  _globals['_DEQUEUEREQUEST']._serialized_start=98
  _globals['_DEQUEUEREQUEST']._serialized_end=114
  _globals['_DEQUEUERESPONSE']._serialized_start=116
  _globals['_DEQUEUERESPONSE']._serialized_end=203
  _globals['_ELECTIONREQUEST']._serialized_start=205
  _globals['_ELECTIONREQUEST']._serialized_end=240
  _globals['_ELECTIONRESPONSE']._serialized_start=242
  _globals['_ELECTIONRESPONSE']._serialized_end=282
  _globals['_COORDINATORREQUEST']._serialized_start=284
  _globals['_COORDINATORREQUEST']._serialized_end=322
  _globals['_COORDINATORRESPONSE']._serialized_start=324
  _globals['_COORDINATORRESPONSE']._serialized_end=362
  _globals['_ORDEREXECUTORSERVICE']._serialized_start=365
  _globals['_ORDEREXECUTORSERVICE']._serialized_end=714
# @@protoc_insertion_point(module_scope)
