{
 "title": "Checkpoint 4",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Fauds passed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 0 },
   "targets": [
    { "expr": "passed_card_fraud_ratio", "legendFormat": "__auto" },
    { "expr": "passed_default_fraud_ratio", "legendFormat": "__auto" },
    { "expr": "passed_user_fraud_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Transaction verifications passed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 0 },
   "targets": [
    { "expr": "verify_card_info_total", "legendFormat": "__auto" },
    { "expr": "verify_items_total", "legendFormat": "__auto" },
    { "expr": "verify_user_data_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Orchestrator jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(orchestrator_service_calls_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "orchestrator_service_calls_count",
     "legendFormat": "__auto"
    },
    { "expr": "orchestrator_service_calls_sum", "legendFormat": "__auto" }
   ]
  }
 ]
}